name: CD - Build and Push Docker

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'extract_folder/**'
      - 'snowflakes/**'

jobs:
  build-and-push:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Download code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telecom-elt-pipeline:latest .
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/telecom-elt-pipeline:${{ github.sha }} .
      
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telecom-elt-pipeline:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/telecom-elt-pipeline:${{ github.sha }}
      
      - name: Success message
        run: |
          echo "Docker image built and pushed successfully!"
          echo "Image name: ${{ secrets.DOCKERHUB_USERNAME }}/telecom-elt-pipeline:latest"
          echo "You can now pull this image on any server using:"
          echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/telecom-elt-pipeline:latest"